"use client";

import { useState } from "react";
import { AlertTriangle, ArrowRight, Bot, Calculator, Database, RefreshCw, Settings2, Sparkles, X } from "lucide-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { BusinessModuleKey } from "@/lib/business-archetypes/types";
import { MotionStagger } from "@/components/motion/motion-stagger";
import { COMMAND_CENTER_ALERTS, COMMAND_CENTER_METRICS, CMV_EVOLUTION } from "@/lib/business-command-center/fixtures";
import type { CommandCenterMetric, MetricCalculationTrace } from "@/lib/business-command-center/types";
import { AskLokatPanel } from "./_ask-lokat-panel";
import { BusinessResultWaterfall } from "./_business-result-waterfall";
import { dashboardStatus, dashboardTokens } from "./_dashboard-design-tokens";

type NavigateFn = (section: BusinessModuleKey, detail?: string) => void;
type Props = { companyName: string; managerMode: boolean; onNavigate: NavigateFn };
const money = (cents: number) => (cents / 100).toLocaleString("pt-BR", { style: "currency", currency: "BRL", maximumFractionDigits: 0 });
const sales = [{ period: "Abr.", vendas: 82000, pedidos: 211 }, { period: "Mai.", vendas: 92200, pedidos: 236 }, { period: "Jun.", vendas: 100000, pedidos: 248 }];
const cash = [{ period: "Hoje", value: 18450 }, { period: "+7d", value: 16900 }, { period: "+15d", value: 19700 }, { period: "+30d", value: 22500 }];
const stock = [{ name: "Central", value: 6800 }, { name: "Cozinha", value: 3200 }];
const PRIMARY = ["sales", "orders", "ticket_average", "cmv_actual", "cmv_gap", "cash_balance"];

export function CommandCenterDashboard({ companyName, managerMode, onNavigate }: Props) {
  const [trace, setTrace] = useState<MetricCalculationTrace | null>(null);
  const [assistantOpen, setAssistantOpen] = useState(false);
  const primary = COMMAND_CENTER_METRICS.filter((metric) => PRIMARY.includes(metric.id));
  const secondary = COMMAND_CENTER_METRICS.filter((metric) => !PRIMARY.includes(metric.id));
  return (
    <MotionStagger className="space-y-4" data-testid="command-center-v2">
      <header className={`${dashboardTokens.elevated} ${dashboardTokens.radius} ${dashboardTokens.cardPadding}`}>
        <div className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between">
          <div className="min-w-0">
            <div className="flex flex-wrap items-center gap-2"><p className="text-[10px] font-black uppercase text-violet-700">Centro de comando</p><span className="rounded-full border border-emerald-200 bg-emerald-50 px-2 py-0.5 text-[10px] font-bold text-emerald-700">Operação acompanhada</span></div>
            <h2 className="mt-1 text-xl font-black tracking-tight text-[#f6f7fb] sm:text-2xl">{companyName}</h2>
            <p className="mt-1 text-xs text-slate-500">Alimentação · Junho de 2026 · comparação com maio · atualizado em 01/07/2026 às 09:00</p>
          </div>
          <div className="flex flex-wrap gap-2">
            <button className={buttonClass}><RefreshCw className="h-3.5 w-3.5" />Atualizar dados</button>
            <button onClick={() => onNavigate("settings")} className={buttonClass}><Settings2 className="h-3.5 w-3.5" />Configurar fontes</button>
            <button onClick={() => setAssistantOpen(true)} className={`${buttonClass} border-violet-600 bg-violet-600 text-white hover:bg-violet-700`}><Bot className="h-3.5 w-3.5" />Pergunte à Lokat</button>
          </div>
        </div>
      </header>

      <SourceStrip onNavigate={onNavigate} />

      <section aria-labelledby="kpi-title">
        <div className="mb-2 flex items-end justify-between"><div><h3 id="kpi-title" className="text-sm font-extrabold text-[#f6f7fb]">Indicadores principais</h3><p className="text-[11px] text-[#8993a8]">Seis números para entender a situação agora.</p></div></div>
        <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-6">{primary.map((metric) => <ExecutiveMetric key={metric.id} metric={metric} onNavigate={onNavigate} onTrace={setTrace} />)}</div>
        <details className="mt-3"><summary className={`${dashboardTokens.focus} cursor-pointer text-xs font-bold text-violet-700`}>Ver indicadores complementares</summary><div className="mt-3 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{secondary.map((metric) => <ExecutiveMetric key={metric.id} metric={metric} onNavigate={onNavigate} onTrace={setTrace} />)}<CompactKpi label="Reserva atual" value="R$ 12.400" detail="67% da recomendação" /><CompactKpi label="Produtos sem ficha" value="1" detail="de 3 produtos" /><CompactKpi label="Margem de contribuição" value="22,0%" detail="Estimativa gerencial" /></div></details>
      </section>

      <div className="grid grid-cols-1 gap-4 xl:grid-cols-12">
        <BusinessResultWaterfall managerMode={managerMode} />
        <ChartPanel className="xl:col-span-5" title="Vendas e pedidos" meta="Abril a junho · cardápio simulado" summary="Vendas e pedidos cresceram no período.">
          <ResponsiveContainer width="100%" height="100%"><LineChart data={sales}><CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" /><XAxis dataKey="period" /><YAxis yAxisId="sales" width={44} /><YAxis yAxisId="orders" orientation="right" width={30} /><Tooltip formatter={(value, name) => name === "Vendas" ? money(Number(value) * 100) : `${value} pedidos`} /><Legend /><Line yAxisId="sales" dataKey="vendas" name="Vendas" stroke="#7c3aed" strokeWidth={2} /><Line yAxisId="orders" dataKey="pedidos" name="Pedidos" stroke="#059669" strokeWidth={2} /></LineChart></ResponsiveContainer>
        </ChartPanel>

        <ChartPanel className="xl:col-span-7" title="CMV real, teórico e meta" meta="Abril a junho · cálculos Lokat" summary="A lacuna aumentou e precisa de investigação, sem indicar uma causa comprovada.">
          <ResponsiveContainer width="100%" height="100%"><LineChart data={CMV_EVOLUTION}><CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" /><XAxis dataKey="period" /><YAxis unit="%" width={38} /><Tooltip formatter={(value) => value === null ? "Indisponível" : `${Number(value).toFixed(1).replace(".", ",")}%`} /><Legend /><Line dataKey="actual" name="Real" stroke="#e11d48" strokeWidth={2} /><Line dataKey="theoretical" name="Teórico" stroke="#7c3aed" strokeWidth={2} /><Line dataKey="target" name="Meta simulada" stroke="#059669" strokeDasharray="4 4" /></LineChart></ResponsiveContainer>
        </ChartPanel>
        <ChartPanel className="xl:col-span-5" title="Saldo de caixa projetado" meta="Próximos 30 dias · financeiro simulado" summary="A projeção não considera eventos ainda não cadastrados.">
          <ResponsiveContainer width="100%" height="100%"><AreaChart data={cash}><defs><linearGradient id="cashFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#7c3aed" stopOpacity={0.3} /><stop offset="1" stopColor="#7c3aed" stopOpacity={0.03} /></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" /><XAxis dataKey="period" /><YAxis width={44} /><Tooltip formatter={(value) => money(Number(value) * 100)} /><Area dataKey="value" name="Saldo" stroke="#7c3aed" fill="url(#cashFill)" /></AreaChart></ResponsiveContainer>
        </ChartPanel>

        <InsightPanel title="Produtos" action="Abrir Produtos e Fichas" onClick={() => onNavigate("products_pricing")} className="xl:col-span-4"><StatLine label="Maior contribuição" value="Smash de Exemplo" /><StatLine label="Mais vendido" value="Combo da Casa" /><StatLine label="Margem baixa" value="Batata Especial" tone="warning" /><div className="mt-3 grid grid-cols-2 gap-2 text-center text-[10px]"><span className="rounded bg-emerald-50 p-2 text-emerald-700">Alta venda · alta margem</span><span className="rounded bg-amber-50 p-2 text-amber-800">Alta venda · baixa margem</span></div></InsightPanel>
        <InsightPanel title="Estoque" action="Abrir Estoque e Compras" onClick={() => onNavigate("stock")} className="xl:col-span-4"><div className="h-28"><ResponsiveContainer width="100%" height="100%"><BarChart data={stock} layout="vertical"><XAxis type="number" hide /><YAxis type="category" dataKey="name" width={52} tick={{ fontSize: 10 }} /><Tooltip formatter={(value) => money(Number(value) * 100)} /><Bar dataKey="value" name="Valor" fill="#7c3aed" radius={[0, 4, 4, 0]} /></BarChart></ResponsiveContainer></div><StatLine label="Itens em reposição" value="3" /><StatLine label="Precisão" value="92%" /></InsightPanel>
        <InsightPanel title="Reserva" action="Abrir Financeiro" onClick={() => onNavigate("finance", "Reserva")} className="xl:col-span-4"><p className="text-2xl font-black">R$ 12.400</p><p className="text-xs text-slate-500">de R$ 18.500 recomendados</p><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full w-[67%] rounded-full bg-violet-600" /></div><p className="mt-2 text-[11px] text-amber-700">Cobertura estimada de 18 dias sem vendas.</p></InsightPanel>

        <section className={`${dashboardTokens.panel} ${dashboardTokens.radius} ${dashboardTokens.cardPadding} xl:col-span-8`}><div className="flex items-center justify-between"><div><h3 className="text-sm font-extrabold">O que precisa da sua atenção</h3><p className="text-[11px] text-slate-500">Hipóteses priorizadas; confirme os dados antes de agir.</p></div><button className="text-xs font-bold text-violet-700">Ver todos os alertas</button></div><div className="mt-3 divide-y divide-slate-100">{COMMAND_CENTER_ALERTS.slice(0, 5).map((alert) => <button key={alert.id} onClick={() => onNavigate(alert.destination, alert.destinationDetail)} className={`${dashboardTokens.focus} flex w-full items-start gap-3 py-3 text-left`}><AlertTriangle className={alert.priority === "high" ? "mt-0.5 h-4 w-4 shrink-0 text-rose-600" : "mt-0.5 h-4 w-4 shrink-0 text-amber-600"} /><span className="min-w-0 flex-1"><strong className="block text-xs">{alert.title}</strong><span className="mt-1 block text-[11px] text-slate-600">{alert.explanation} {alert.impact}</span><span className="mt-1 block text-[10px] font-bold text-violet-700">{alert.action} · {alert.suggestedOwner}</span></span><ArrowRight className="h-4 w-4 text-slate-400" /></button>)}</div></section>
        <section className={`${dashboardTokens.panel} ${dashboardTokens.radius} ${dashboardTokens.cardPadding} xl:col-span-4`}><div className="flex items-center gap-2"><Database className="h-4 w-4 text-violet-600" /><h3 className="text-sm font-extrabold">Qualidade dos dados</h3></div><p className="mt-3 text-3xl font-black">92%</p><p className="text-xs text-slate-500">cobertura geral do exemplo</p><div className="mt-4 space-y-2"><StatLine label="Registros incluídos" value="248" /><StatLine label="Excluídos" value="7" /><StatLine label="Fontes desatualizadas" value="1" tone="warning" /></div></section>
      </div>

      <section className={`${dashboardTokens.panel} ${dashboardTokens.radius} p-3`} aria-label="Ações rápidas"><div className="flex flex-wrap items-center gap-2"><span className="mr-1 text-[10px] font-black uppercase text-slate-500">Ações rápidas</span>{["Cadastrar produto", "Criar ficha técnica", "Registrar inventário", "Adicionar compra", "Importar planilha", "Configurar fonte"].map((label) => <button key={label} className={buttonClass} title="Ação demonstrativa; nenhuma informação será salva"><Sparkles className="h-3 w-3" />{label}</button>)}<button onClick={() => setAssistantOpen(true)} className={buttonClass}><Bot className="h-3 w-3" />Perguntar à Lokat</button></div></section>
      {trace && <TraceDrawer trace={trace} onClose={() => setTrace(null)} onNavigate={onNavigate} />}
      <AskLokatPanel open={assistantOpen} onClose={() => setAssistantOpen(false)} onNavigate={onNavigate} />
    </MotionStagger>
  );
}

const buttonClass = `${dashboardTokens.focus} ${dashboardTokens.motion} inline-flex min-h-9 items-center gap-1.5 rounded-md border border-[#3a4354] bg-[#1d2230] px-3 py-2 text-xs font-bold text-[#bcc4d4] hover:border-violet-400/50 hover:text-white disabled:cursor-not-allowed disabled:opacity-70`;
function SourceStrip({ onNavigate }: { onNavigate: (section: BusinessModuleKey) => void }) { const sources = [{ name: "Cardápio digital", state: "Não testado", style: dashboardStatus.warning }, { name: "Planilha", state: "Exemplo importado", style: dashboardStatus.informative }, { name: "Diagnóstico", state: "Precisa configurar", style: dashboardStatus.manual }, { name: "Estoque", state: "Simulado", style: dashboardStatus.simulated }, { name: "Fichas", state: "Simulado", style: dashboardStatus.simulated }, { name: "Cálculos Lokat", state: "Disponível", style: dashboardStatus.positive }]; return <section className={`${dashboardTokens.panel} ${dashboardTokens.radius} grid overflow-hidden sm:grid-cols-2 xl:grid-cols-6`} aria-label="Fontes e integrações">{sources.map((source) => <button key={source.name} onClick={() => onNavigate("settings")} className={`${dashboardTokens.focus} border-b border-slate-100 px-3 py-2.5 text-left last:border-0 sm:border-r xl:border-b-0`}><span className="block text-[10px] text-slate-500">{source.name}</span><span className={`mt-1 inline-flex rounded-full border px-2 py-0.5 text-[9px] font-bold ${source.style}`}>{source.state}</span></button>)}</section>; }
function ExecutiveMetric({ metric, onNavigate, onTrace }: { metric: CommandCenterMetric; onNavigate: NavigateFn; onTrace: (trace: MetricCalculationTrace) => void }) { return <article className={`${dashboardTokens.panel} ${dashboardTokens.radius} p-4 transition-colors hover:border-[#3a4354] hover:bg-[#171b26]`}><button onClick={() => onNavigate(metric.destination, metric.destinationDetail)} className={`${dashboardTokens.focus} w-full text-left`} title={metric.tooltip}><div className="flex items-start justify-between gap-2"><p className="text-[11px] font-bold text-[#bcc4d4]">{metric.label}</p>{metric.alert && <AlertTriangle className="h-3.5 w-3.5 text-amber-300" />}</div><p className="mt-1 text-xl font-black text-[#f6f7fb]">{metric.formattedValue}</p><p className="text-[10px] font-bold text-emerald-300">{metric.comparison}</p><svg aria-hidden="true" viewBox="0 0 80 16" className="mt-3 h-4 w-full text-violet-400"><polyline points="0,13 16,10 32,11 48,5 64,7 80,2" fill="none" stroke="currentColor" strokeWidth="2" /></svg></button><div className="mt-2 border-t border-[#272d3a] pt-2 text-[10px] text-[#8993a8]"><p>{metric.period} · {metric.source}</p><p>Atualizado em 01/07 · {metric.state === "simulated" ? "Simulado" : "Calculado"}</p></div><button onClick={() => onTrace(metric.trace)} className={`${dashboardTokens.focus} mt-2 inline-flex items-center gap-1 text-[10px] font-bold text-violet-300 hover:text-violet-200`}><Calculator className="h-3 w-3" />Como calculamos</button></article>; }
function CompactKpi({ label, value, detail }: { label: string; value: string; detail: string }) { return <article className={`${dashboardTokens.panel} ${dashboardTokens.radius} p-4`}><p className="text-[11px] font-bold text-slate-500">{label}</p><p className="mt-1 text-xl font-black">{value}</p><p className="mt-1 text-[10px] text-slate-500">{detail} · Exemplo simulado</p></article>; }
function ChartPanel({ title, meta, summary, className, children }: { title: string; meta: string; summary: string; className: string; children: React.ReactNode }) { return <section className={`${dashboardTokens.panel} ${dashboardTokens.radius} ${dashboardTokens.cardPadding} ${className}`}><h3 className="text-sm font-extrabold">{title}</h3><p className="text-[10px] text-slate-500">{meta}</p><div className="mt-3 h-56 sm:h-64">{children}</div><p className="mt-2 text-[11px] text-slate-600">{summary}</p></section>; }
function InsightPanel({ title, action, onClick, className, children }: { title: string; action: string; onClick: () => void; className: string; children: React.ReactNode }) { return <section className={`${dashboardTokens.panel} ${dashboardTokens.radius} ${dashboardTokens.cardPadding} ${className}`}><h3 className="text-sm font-extrabold">{title}</h3><div className="mt-3">{children}</div><button onClick={onClick} className={`${dashboardTokens.focus} mt-4 inline-flex items-center gap-1 text-xs font-bold text-violet-700`}>{action}<ArrowRight className="h-3.5 w-3.5" /></button></section>; }
function StatLine({ label, value, tone }: { label: string; value: string; tone?: "warning" }) { return <div className="flex items-center justify-between gap-3 border-b border-slate-100 py-2 text-xs"><span className="text-slate-500">{label}</span><strong className={tone === "warning" ? "text-amber-700" : "text-slate-900"}>{value}</strong></div>; }
function TraceDrawer({ trace, onClose, onNavigate }: { trace: MetricCalculationTrace; onClose: () => void; onNavigate: NavigateFn }) { return <div className="fixed inset-0 z-[80] bg-slate-950/40" role="dialog" aria-modal="true" aria-labelledby="trace-title"><aside className="ml-auto h-full w-full max-w-lg overflow-y-auto bg-white p-5 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-[10px] font-black uppercase text-violet-700">Como calculamos</p><h3 id="trace-title" className="text-lg font-black">{trace.metricLabel}</h3></div><button onClick={onClose} aria-label="Fechar rastreabilidade" className={dashboardTokens.focus}><X className="h-5 w-5" /></button></div><div className="mt-5 space-y-4 text-xs"><section><p className="font-bold">Resultado</p><p className="mt-1 text-2xl font-black">{trace.result.toLocaleString("pt-BR")} <span className="text-sm text-slate-500">{trace.unit}</span></p></section><section><p className="font-bold">Fórmula</p><p className="mt-1 rounded-md bg-slate-50 p-3 font-mono text-[11px]">{trace.formulaExpression}</p></section><section><p className="font-bold">Valores e origens</p>{trace.inputs.map((input) => <div key={input.label} className="mt-2 flex justify-between gap-3 border-b pb-2"><span>{input.label}<small className="block text-slate-500">Fonte: {input.source}</small></span><strong>{input.unit === "centavos" ? money(input.value) : `${input.value.toLocaleString("pt-BR")} ${input.unit}`}</strong></div>)}</section><dl className="grid grid-cols-2 gap-3"><div><dt className="text-slate-500">Período</dt><dd>01/06 a 30/06/2026</dd></div><div><dt className="text-slate-500">Cobertura</dt><dd>{(trace.coverage * 100).toFixed(0)}%</dd></div><div><dt className="text-slate-500">Incluídos</dt><dd>{trace.includedRecords}</dd></div><div><dt className="text-slate-500">Excluídos</dt><dd>{trace.excludedRecords}</dd></div><div><dt className="text-slate-500">Versão</dt><dd>{trace.calculationVersion}</dd></div><div><dt className="text-slate-500">Atualizado</dt><dd>01/07/2026</dd></div></dl>{trace.warnings.map((warning) => <p key={warning} className="rounded-md bg-amber-50 p-3 text-amber-800">{warning}</p>)}</div><div className="mt-6 flex gap-2"><button onClick={() => onNavigate(trace.linksToFixData[0].destination, trace.linksToFixData[0].destinationDetail)} className="rounded-md bg-violet-600 px-3 py-2 text-xs font-bold text-white">Corrigir base</button><button onClick={() => onNavigate(trace.linksToFixData[0].destination, trace.linksToFixData[0].destinationDetail)} className="rounded-md border border-slate-200 px-3 py-2 text-xs font-bold">Abrir setor</button></div></aside></div>; }
