"use client";
import { useEffect, useRef, useState } from "react";
import { canUseDecorativeWebGL } from "@/lib/motion/motion-preferences";
export default function LokatIntelligenceOrb() {
  const host = useRef<HTMLDivElement>(null); const [fallback, setFallback] = useState(true);
  useEffect(() => { const container = host.current; if (!container || !canUseDecorativeWebGL()) return; let disposed = false; let frame = 0; let visible = true; let observer: IntersectionObserver | undefined; let renderer: import("three").WebGLRenderer | undefined; let geometry: import("three").IcosahedronGeometry | undefined; let material: import("three").MeshStandardMaterial | undefined;
    void import("three").then((THREE) => { if (disposed) return; try { const scene = new THREE.Scene(); const camera = new THREE.PerspectiveCamera(38, 1, 0.1, 20); camera.position.z = 4; renderer = new THREE.WebGLRenderer({ alpha: true, antialias: true, powerPreference: "low-power" }); renderer.setPixelRatio(Math.min(devicePixelRatio, 1.5)); renderer.setSize(176, 176, false); renderer.domElement.setAttribute("aria-hidden", "true"); renderer.domElement.addEventListener("webglcontextlost", (event) => { event.preventDefault(); setFallback(true); }); container.appendChild(renderer.domElement); geometry = new THREE.IcosahedronGeometry(1.05, 2); material = new THREE.MeshStandardMaterial({ color: 0x7c3aed, emissive: 0x2e1065, roughness: 0.35, metalness: 0.25, wireframe: true }); const orb = new THREE.Mesh(geometry, material); scene.add(orb); scene.add(new THREE.AmbientLight(0xffffff, 1.4)); const light = new THREE.PointLight(0xc4b5fd, 4, 10); light.position.set(2, 2, 3); scene.add(light); setFallback(false); const render = () => { if (disposed) return; if (visible && !document.hidden) { orb.rotation.y += 0.0035; orb.rotation.x += 0.0015; renderer?.render(scene, camera); } frame = requestAnimationFrame(render); }; observer = new IntersectionObserver(([entry]) => { visible = entry.isIntersecting; }); observer.observe(container); render(); } catch { setFallback(true); } });
    return () => { disposed = true; cancelAnimationFrame(frame); observer?.disconnect(); geometry?.dispose(); material?.dispose(); renderer?.dispose(); renderer?.domElement.remove(); };
  }, []);
  return <div ref={host} className="relative grid h-44 w-44 place-items-center" data-lokat-orb data-webgl-fallback={fallback}>{fallback && <div className="h-24 w-24 rounded-full border border-violet-400/40 bg-violet-500/10 shadow-[0_0_36px_rgba(139,92,246,0.22)]" aria-label="Inteligência Lokat" />}</div>;
}
