import type { GlossaryEntry } from "./types";

export const GLOSSARY: GlossaryEntry[] = [
  {
    id: "faturamento", simpleName: "Tudo que foi vendido", technicalName: "Faturamento bruto",
    explanation: "Soma de todas as vendas antes de qualquer desconto, cancelamento ou taxa.",
    formula: "Soma das vendas do período.",
    example: "Vendeu R$ 10.000 em produtos no mês → faturamento bruto de R$ 10.000, mesmo que parte tenha sido cancelada depois.",
    commonMistakes: ["Confundir com o dinheiro que realmente entrou no caixa."],
    relatedTerms: ["receita_reconhecida", "receita_liquida"],
  },
  {
    id: "receita_reconhecida", simpleName: "O que a empresa realmente recebeu", technicalName: "Receita reconhecida",
    explanation: "Valor pago pelo cliente somado aos subsídios que a plataforma efetivamente pagou.",
    formula: "Valor pago pelo cliente + subsídios pagos pela plataforma.",
    example: "Cliente pagou R$ 30 num produto de R$ 40, e o app completou R$ 5 → receita reconhecida de R$ 35.",
    commonMistakes: ["Achar que o preço de tabela é o que a empresa recebe."],
    relatedTerms: ["faturamento", "receita_liquida"],
  },
  {
    id: "receita_liquida", simpleName: "O que sobra depois de descontos e estornos", technicalName: "Receita líquida",
    explanation: "Receita reconhecida menos devoluções, estornos e chargebacks.",
    formula: "Receita reconhecida − devoluções/estornos − chargebacks.",
    example: "Receita reconhecida de R$ 35, com R$ 2 de chargeback → receita líquida de R$ 33.",
    commonMistakes: ["Ignorar chargebacks e devoluções ao calcular margem."],
    relatedTerms: ["receita_reconhecida", "margem_contribuicao"],
  },
  {
    id: "custo_direto", simpleName: "Quanto custa produzir ou entregar", technicalName: "Custo direto (CMV / custo do serviço vendido)",
    explanation: "Matéria-prima, mercadoria, embalagem, frete proporcional e insumos diretamente ligados à entrega.",
    formula: "Soma dos custos diretos ligados à unidade vendida.",
    example: "Um prato custa R$ 16 em ingredientes e embalagem para ser vendido a R$ 40.",
    commonMistakes: ["Incluir despesas fixas (aluguel, folha) dentro do custo direto."],
    relatedTerms: ["cmv", "margem_contribuicao"],
  },
  {
    id: "cmv", simpleName: "Nome do custo direto no varejo", technicalName: "CMV — Custo da Mercadoria Vendida",
    explanation: "É o nome mais comum para custo direto quando o negócio revende produtos prontos.",
    formula: "Estoque inicial + compras − estoque final (por período), ou custo unitário × quantidade vendida.",
    example: "Comprou uma peça por R$ 50 e vendeu por R$ 120 → CMV de R$ 50 nessa venda.",
    commonMistakes: ["Confundir CMV com o preço de venda."],
    relatedTerms: ["custo_direto"],
  },
  {
    id: "csv", simpleName: "Nome do custo direto em serviços", technicalName: "CSV — Custo do Serviço Vendido",
    explanation: "Equivalente ao CMV, mas para negócios que vendem serviço em vez de produto físico.",
    formula: "Custo direto de mão de obra e insumos ligados à entrega do serviço.",
    example: "Uma consultoria de R$ 2.000 com R$ 400 de horas técnicas diretas → CSV de R$ 400.",
    commonMistakes: ["Achar que serviço não tem custo direto."],
    relatedTerms: ["custo_direto"],
  },
  {
    id: "despesas_fixas", simpleName: "O que a empresa gasta todo mês, vendendo ou não", technicalName: "Despesas fixas",
    explanation: "Custos que não variam com o volume de vendas no curto prazo: aluguel, folha, sistemas, etc.",
    formula: "Soma das despesas fixas do período.",
    example: "Aluguel de R$ 3.000 + folha de R$ 8.000 = R$ 11.000 de despesas fixas no mês.",
    commonMistakes: ["Misturar despesas fixas com despesas variáveis."],
    relatedTerms: ["resultado_operacional", "ponto_equilibrio"],
  },
  {
    id: "despesas_variaveis", simpleName: "Custos que só existem porque a venda aconteceu", technicalName: "Despesas variáveis",
    explanation: "Taxas de marketplace, cartão, impostos sobre vendas, entrega subsidiada, comissões.",
    formula: "Soma das despesas ligadas ao volume de vendas.",
    example: "Taxa de app de 12% sobre uma venda de R$ 40 = R$ 4,80 de despesa variável.",
    commonMistakes: ["Tratar despesa variável como se fosse fixa."],
    relatedTerms: ["margem_contribuicao"],
  },
  {
    id: "margem_bruta", simpleName: "Quanto sobra só descontando o custo direto", technicalName: "Margem bruta",
    explanation: "Receita líquida menos custo direto, antes de descontar despesas variáveis.",
    formula: "Receita líquida − custo direto.",
    example: "Receita líquida de R$ 33, custo direto de R$ 16 → margem bruta de R$ 17.",
    commonMistakes: ["Confundir margem bruta com margem de contribuição (que já desconta despesas variáveis)."],
    relatedTerms: ["margem_contribuicao"],
  },
  {
    id: "margem_contribuicao", simpleName: "Quanto sobra depois da venda", technicalName: "Margem de contribuição",
    explanation: "O valor que permanece depois do custo para entregar, taxas e outras despesas variáveis — antes das despesas fixas.",
    formula: "Receita líquida − custo direto − despesas variáveis.",
    example: "Receita líquida de R$ 33, custo direto de R$ 16, despesas variáveis de R$ 5 → margem de contribuição de R$ 12.",
    commonMistakes: ["Chamar margem de contribuição de lucro."],
    relatedTerms: ["resultado_operacional", "ponto_equilibrio"],
  },
  {
    id: "resultado_operacional", simpleName: "O que sobra depois de tudo que é fixo", technicalName: "Resultado operacional estimado",
    explanation: "Margem de contribuição menos despesas fixas — uma estimativa operacional, não o lucro líquido final.",
    formula: "Margem de contribuição − despesas fixas.",
    example: "Margem de contribuição de R$ 12.000 no mês, despesas fixas de R$ 11.000 → resultado operacional de R$ 1.000.",
    commonMistakes: ["Chamar resultado operacional de lucro líquido — faltam impostos sobre o lucro e itens não operacionais."],
    relatedTerms: ["lucro_liquido", "margem_contribuicao"],
  },
  {
    id: "lucro_liquido", simpleName: "O que realmente sobra no fim de tudo", technicalName: "Lucro líquido",
    explanation: "Resultado depois de todos os impostos sobre o lucro, depreciação e itens não operacionais — não calculado nesta versão.",
    formula: "Resultado operacional − impostos sobre o lucro − outras despesas/receitas não operacionais.",
    example: "Esta versão do Motor LOKAT calcula resultado operacional estimado, não o lucro líquido contábil final.",
    commonMistakes: ["Usar resultado operacional e lucro líquido como sinônimos."],
    relatedTerms: ["resultado_operacional"],
  },
  {
    id: "fluxo_caixa", simpleName: "Dinheiro entrando e saindo de verdade", technicalName: "Fluxo de caixa",
    explanation: "Uma venda pode existir antes de o dinheiro realmente entrar — fluxo de caixa acompanha o dinheiro de fato.",
    formula: "Saldo inicial + entradas − saídas (previstas ou realizadas).",
    example: "Vendeu R$ 5.000 a prazo — o faturamento existe, mas o caixa só recebe quando o cliente pagar.",
    commonMistakes: ["Confundir faturamento com entrada de caixa."],
    relatedTerms: ["capital_giro", "forecast"],
  },
  {
    id: "forecast", simpleName: "Previsão do que deve acontecer", technicalName: "Forecast",
    explanation: "Projeção de entradas, saídas ou vendas futuras com base em premissas.",
    formula: "Depende do método — pode ser baseado em histórico, meta ou tendência.",
    example: "Forecast de caixa para os próximos 3 meses com base na média dos últimos 6.",
    commonMistakes: ["Tratar forecast como garantia em vez de estimativa."],
    relatedTerms: ["fluxo_caixa"],
  },
  {
    id: "capital_giro", simpleName: "Reserva para aguentar os meses ruins", technicalName: "Capital de giro",
    explanation: "Quanto o negócio deveria ter guardado para cobrir despesas por um período sem depender de vendas imediatas.",
    formula: "Despesas médias mensais × meses desejados de reserva.",
    example: "Despesas médias de R$ 10.000/mês, meta de 3 meses de reserva → capital de giro sugerido de R$ 30.000.",
    commonMistakes: ["Não separar capital de giro do caixa do dia a dia."],
    relatedTerms: ["fluxo_caixa"],
  },
  {
    id: "ponto_equilibrio", simpleName: "Quanto precisa vender para não ter prejuízo", technicalName: "Ponto de equilíbrio",
    explanation: "O faturamento (ou quantidade) mínimo para cobrir despesas fixas com a margem de contribuição gerada.",
    formula: "Despesas fixas ÷ percentual da margem de contribuição.",
    example: "Despesas fixas de R$ 11.000, margem de contribuição de 40% → ponto de equilíbrio de R$ 27.500.",
    commonMistakes: ["Achar que ponto de equilíbrio é a meta de vendas ideal, e não o mínimo para não ter prejuízo."],
    relatedTerms: ["margem_contribuicao", "despesas_fixas"],
  },
  {
    id: "ticket_medio", simpleName: "Quanto vale, em média, cada venda", technicalName: "Ticket médio",
    explanation: "O valor médio de cada pedido ou venda no período.",
    formula: "Faturamento bruto ÷ quantidade de pedidos.",
    example: "R$ 10.000 em vendas com 250 pedidos → ticket médio de R$ 40.",
    commonMistakes: ["Calcular sem contar pedidos cancelados de forma consistente."],
    relatedTerms: ["ponto_equilibrio"],
  },
  {
    id: "cac", simpleName: "Quanto custou conquistar um cliente novo", technicalName: "CAC — Custo de Aquisição de Cliente",
    explanation: "O investimento em aquisição dividido pelo número de novos clientes conquistados.",
    formula: "Investimento em aquisição ÷ novos clientes conquistados.",
    example: "Investiu R$ 3.000 numa campanha e conquistou 60 clientes novos → CAC de R$ 50.",
    commonMistakes: ["Incluir clientes recorrentes na conta de 'novos clientes'."],
    relatedTerms: ["ltv", "payback"],
  },
  {
    id: "ltv", simpleName: "Quanto um cliente pode deixar ao longo do tempo", technicalName: "LTV — Lifetime Value (de receita)",
    explanation: "Estimativa de quanto um cliente vai gerar em receita ao longo do relacionamento.",
    formula: "Ticket médio × número de compras futuras esperadas.",
    example: "Ticket médio de R$ 40, cliente compra 5 vezes → LTV de receita de R$ 200.",
    commonMistakes: ["Confundir LTV de receita com LTV de contribuição (que já desconta custos)."],
    relatedTerms: ["ltv_contribuicao", "cac"],
  },
  {
    id: "ltv_contribuicao", simpleName: "Quanto desse cliente sobra de verdade", technicalName: "LTV de contribuição",
    explanation: "O LTV de receita ajustado pela margem de contribuição esperada — o que realmente sobra desse cliente.",
    formula: "LTV de receita × percentual médio da margem de contribuição.",
    example: "LTV de receita de R$ 200, margem de contribuição de 40% → LTV de contribuição de R$ 80.",
    commonMistakes: ["Comparar CAC direto com LTV de receita em vez de LTV de contribuição."],
    relatedTerms: ["ltv", "cac"],
  },
  {
    id: "payback", simpleName: "Quanto tempo/quantas compras até recuperar o investimento", technicalName: "Payback",
    explanation: "Quantas compras (ou meses) até o valor gerado pelo cliente recuperar o CAC investido.",
    formula: "CAC ÷ (ticket médio futuro × margem de contribuição futura).",
    example: "CAC de R$ 50, cada compra futura deixa R$ 16 de contribuição → payback em pouco mais de 3 compras.",
    commonMistakes: ["Ignorar payback e olhar só para LTV/CAC."],
    relatedTerms: ["cac", "ltv_contribuicao"],
  },
  {
    id: "churn", simpleName: "Clientes que somem", technicalName: "Churn",
    explanation: "A taxa de clientes que deixam de comprar ou cancelam em um período.",
    formula: "Clientes perdidos no período ÷ clientes no início do período.",
    example: "Começou o mês com 100 clientes ativos e perdeu 8 → churn de 8%.",
    commonMistakes: ["Não diferenciar churn voluntário de involuntário (ex.: cartão recusado)."],
    relatedTerms: ["recorrencia", "ltv"],
  },
  {
    id: "recorrencia", simpleName: "Clientes que voltam a comprar", technicalName: "Recorrência",
    explanation: "A frequência com que os clientes repetem a compra no período analisado.",
    formula: "Clientes que compraram mais de uma vez ÷ total de clientes no período.",
    example: "De 100 clientes, 30 compraram de novo no mês → recorrência de 30%.",
    commonMistakes: ["Confundir recorrência com retenção de assinatura (são conceitos próximos, não idênticos)."],
    relatedTerms: ["churn", "ltv"],
  },
  {
    id: "perdas", simpleName: "Dinheiro que se perde sem virar venda", technicalName: "Perdas",
    explanation: "Desperdício, quebra, roubo, extravio, cancelamento, devolução, inadimplência e outros custos que não geram receita.",
    formula: "Depende da categoria — normalmente soma de ocorrências no período.",
    example: "Um restaurante perdeu R$ 400 em ingredientes vencidos no mês.",
    commonMistakes: ["Não separar perdas por categoria, dificultando a ação corretiva."],
    relatedTerms: ["custo_direto"],
  },
  {
    id: "inadimplencia", simpleName: "Cliente que não paga", technicalName: "Inadimplência",
    explanation: "Valores que deveriam ter sido recebidos e não foram, dentro do prazo esperado.",
    formula: "Valor em atraso ÷ total a receber no período.",
    example: "De R$ 20.000 a receber, R$ 1.000 estão em atraso há mais de 30 dias → inadimplência de 5%.",
    commonMistakes: ["Tratar inadimplência como perda definitiva sem tentar cobrança."],
    relatedTerms: ["fluxo_caixa", "perdas"],
  },
  {
    id: "markup", simpleName: "Multiplicador sobre o custo", technicalName: "Markup",
    explanation: "Um jeito alternativo (não usado como principal nesta versão) de calcular preço multiplicando o custo por um fator fixo.",
    formula: "Preço = Custo × fator de markup.",
    example: "Custo de R$ 20 com markup de 3x → preço de R$ 60.",
    commonMistakes: ["Usar markup sem considerar despesas fixas e variáveis reais do negócio."],
    relatedTerms: ["margem_lucro"],
  },
  {
    id: "margem_lucro", simpleName: "Percentual que o preço representa de lucro", technicalName: "Margem de lucro (sobre o preço)",
    explanation: "O percentual do preço de venda que corresponde a lucro desejado, usado na metodologia de precificação desta versão.",
    formula: "Margem desejada ÷ preço de venda.",
    example: "Margem desejada de 20% embutida no preço final calculado.",
    commonMistakes: ["Confundir margem sobre o preço com margem sobre o custo (markup)."],
    relatedTerms: ["markup"],
  },
];

export function findGlossaryEntry(id: string): GlossaryEntry | undefined {
  return GLOSSARY.find((g) => g.id === id);
}
