import fs from "node:fs";
import path from "node:path";
const root = path.resolve(process.cwd(), "src/app/admin/meu-negocio");
const ui = fs.readFileSync(path.join(root, "_market-pricing.tsx"), "utf8");
const center = fs.readFileSync(path.join(root, "_cmv-center.tsx"), "utf8");
let passed = 0, failed = 0;
const assert = (condition: boolean, label: string) => { if (condition) { passed++; console.log(`  ok - ${label}`); } else { failed++; console.error(`  FAIL - ${label}`); } };
assert(center.includes("Mercado e concorrência") && center.includes("Simulador de preço"), "novas áreas integradas");
assert(ui.includes("PreÃ§o atual") || ui.includes("Preço atual"), "preço atual separado");
assert(ui.includes("Faixa de mercado"), "faixa de mercado visível");
assert(ui.includes("Nenhum cenÃ¡rio Ã© aplicado automaticamente") || ui.includes("Nenhum cenário é aplicado automaticamente"), "sem aplicação automática");
assert(ui.includes("Concorrente A") === false, "nomes vêm de fixtures, não hardcode de UI");
assert(ui.includes("EXEMPLO SIMULADO"), "demonstração identificada");
assert(ui.includes("overflow-x-auto"), "tabelas tratam overflow");
assert(!ui.includes("fetch("), "sem pesquisa externa");
assert(!ui.includes("SUPABASE") && !ui.includes("process.env"), "sem persistência ou segredo");
assert(ui.includes("Amostras, comparabilidade e limitações"), "modo gestor mostra limitações");
assert(ui.includes("Preço médio realizado e canais"), "canais e preço realizado");
assert(ui.includes("Efeito do mix de vendas"), "efeito do mix integrado");
console.log(`[result] ${passed} passed, ${failed} failed`); if (failed) process.exitCode = 1;
