export interface StockGlossaryEntry {
  id: string;
  /** Linguagem simples primeiro — o termo técnico vem entre parênteses no próprio texto de exibição. */
  simpleLabel: string;
  technicalTerm: string;
  whatIsIt: string;
  howCalculated: string;
  whyItMatters: string;
  whatCanChangeIt: string;
  whatCanUserDo: string;
}

export const STOCK_GLOSSARY: StockGlossaryEntry[] = [
  {
    id: "cmv-real",
    simpleLabel: "Quanto realmente foi consumido",
    technicalTerm: "CMV real",
    whatIsIt: "O valor de insumos que efetivamente saiu do estoque no período, comparado às vendas.",
    howCalculated: "Estoque inicial + compras − estoque final, dividido pelas vendas do período.",
    whyItMatters: "É o número que realmente aconteceu no caixa — a base de comparação para saber se o negócio está gastando mais insumo do que deveria.",
    whatCanChangeIt: "Perdas, cortesias, consumo interno, movimentação não registrada, erro de contagem ou vendas maiores/menores que o normal.",
    whatCanUserDo: "Comparar com o CMV teórico (lacuna de CMV) para decidir se vale investigar mais a fundo.",
  },
  {
    id: "cmv-teorico",
    simpleLabel: "Quanto deveria ter sido consumido",
    technicalTerm: "CMV teórico",
    whatIsIt: "O valor de insumos que as fichas técnicas dizem que DEVERIAM ter sido usados, dado o que foi vendido.",
    howCalculated: "Soma do custo de ingredientes de cada ficha técnica multiplicado pela quantidade vendida de cada produto.",
    whyItMatters: "É a referência 'no papel' — só é confiável se as fichas técnicas estiverem atualizadas e as porções servidas baterem com o padrão.",
    whatCanChangeIt: "Fichas técnicas desatualizadas, mudança de fornecedor sem atualizar custo, porção real diferente da cadastrada.",
    whatCanUserDo: "Manter as fichas técnicas atualizadas é o que torna esse número confiável.",
  },
  {
    id: "lacuna-cmv",
    simpleLabel: "Consumo não explicado",
    technicalTerm: "Lacuna de CMV",
    whatIsIt: "A diferença entre o que realmente foi consumido (CMV real) e o que deveria ter sido consumido (CMV teórico).",
    howCalculated: "CMV real menos CMV teórico, em valor (R$) e em pontos percentuais.",
    whyItMatters: "Uma lacuna grande e recorrente é um sinal de alerta — mas nunca uma prova isolada de problema.",
    whatCanChangeIt: "Ficha técnica desatualizada, porção acima do padrão, perdas, cortesias, consumo interno, erro de compra ou erro de contagem.",
    whatCanUserDo: "Investigar as causas mais prováveis antes de tirar conclusões — a lacuna aponta ONDE olhar, não o motivo.",
  },
  {
    id: "margem-contribuicao",
    simpleLabel: "Quanto cada venda ajuda a pagar a empresa",
    technicalTerm: "Margem de contribuição",
    whatIsIt: "O que sobra do preço de venda depois de descontar o custo direto do produto (ingredientes + embalagem).",
    howCalculated: "Preço praticado menos custo total do produto (ingredientes + embalagem).",
    whyItMatters: "É o valor que sobra para pagar despesas fixas, impostos e, no fim, gerar lucro — mas ainda não é lucro líquido.",
    whatCanChangeIt: "Mudança no preço de venda, no custo dos ingredientes, ou no custo de embalagem.",
    whatCanUserDo: "Comparar a margem entre produtos ajuda a decidir o que vale mais a pena vender/destacar.",
  },
  {
    id: "popularidade-produto",
    simpleLabel: "Participação do produto nas vendas",
    technicalTerm: "Popularidade",
    whatIsIt: "A parcela da quantidade total vendida que pertence a um produto no período.",
    howCalculated: "Quantidade vendida do produto dividida pela quantidade total vendida do menu.",
    whyItMatters: "Ajuda a separar itens que sustentam o volume daqueles que têm pouca saída.",
    whatCanChangeIt: "Período, disponibilidade, posição no cardápio, preço, promoção e canal de venda.",
    whatCanUserDo: "Registrar a regra usada e comparar janelas compatíveis antes de mudar o cardápio.",
  },
  {
    id: "engenharia-cardapio",
    simpleLabel: "Análise entre popularidade e margem",
    technicalTerm: "Engenharia de cardápio",
    whatIsIt: "Uma matriz que cruza o quanto cada produto vende com quanto cada unidade ajuda a pagar a empresa.",
    howCalculated: "Compara popularidade e margem de contribuição com limites configurados.",
    whyItMatters: "Orienta testes de preço, comunicação, composição e disponibilidade sem olhar só faturamento.",
    whatCanChangeIt: "Mix vendido, custos, taxas, descontos, preço e regra de corte escolhida.",
    whatCanUserDo: "Testar uma ação por vez e nunca retirar um produto apenas por uma janela curta.",
  },
  {
    id: "cobertura-cmv",
    simpleLabel: "Percentual das vendas incluído no cálculo",
    technicalTerm: "Cobertura do CMV",
    whatIsIt: "Quanto das vendas, fichas, estoque, compras e período possui dados suficientes para calcular o CMV.",
    howCalculated: "Composição explícita das coberturas de vendas, fichas, estoque, compras e consistência do período.",
    whyItMatters: "Um CMV preciso sobre poucos produtos pode representar mal a operação inteira.",
    whatCanChangeIt: "Produtos sem ficha, inventários incompletos, compras ausentes e períodos desalinhados.",
    whatCanUserDo: "Completar primeiro os dados que cobrem maior faturamento.",
  },
  {
    id: "politica-cmv",
    simpleLabel: "Regra usada para decidir o que entra no cálculo",
    technicalTerm: "Política de CMV",
    whatIsIt: "O conjunto de escolhas sobre vendas, embalagem, taxas, status, inventário, período e meta.",
    howCalculated: "Não é um número: é a configuração usada por todas as fórmulas do período.",
    whyItMatters: "Duas empresas podem obter resultados diferentes porque adotam políticas diferentes.",
    whatCanChangeIt: "Estratégia, canal, modelo contábil, formato do negócio e decisão do responsável financeiro.",
    whatCanUserDo: "Documentar a política, aplicar a mesma regra em períodos comparáveis e revisar com o financeiro.",
  },
  {
    id: "fator-correcao",
    simpleLabel: "Perda entre o peso comprado e o utilizável",
    technicalTerm: "Fator de correção",
    whatIsIt: "Quanto do peso comprado de um ingrediente se perde na limpeza/preparo antes de ir para a receita.",
    howCalculated: "Peso bruto (como comprado) dividido pelo peso líquido (já limpo, pronto para uso).",
    whyItMatters: "Sem esse ajuste, o custo real de um ingrediente é subestimado — comprar 130 g para usar 100 g custa mais por grama útil do que parece.",
    whatCanChangeIt: "Qualidade do insumo, técnica de limpeza/corte, tipo de corte comprado.",
    whatCanUserDo: "Atualizar o fator de correção sempre que trocar de fornecedor ou técnica de preparo.",
  },
  {
    id: "cobertura-estoque",
    simpleLabel: "Quantidade disponível antes de uma nova compra",
    technicalTerm: "Cobertura de estoque",
    whatIsIt: "Por quantos dias o estoque atual de um item dura, no ritmo de consumo médio.",
    howCalculated: "Estoque disponível dividido pelo consumo médio diário.",
    whyItMatters: "Ajuda a decidir quando comprar sem esperar faltar o insumo no meio de uma produção.",
    whatCanChangeIt: "Mudança no ritmo de vendas, promoções, sazonalidade, atraso de fornecedor.",
    whatCanUserDo: "Usar a cobertura junto com o ponto de reposição para decidir a quantidade e o momento da próxima compra.",
  },
  // ── Financeiro (Fase 17 — fluxo de caixa, reserva, capital de giro) ──────
  {
    id: "fluxo-caixa",
    simpleLabel: "Entrada e saída real de dinheiro",
    technicalTerm: "Fluxo de caixa",
    whatIsIt: "O dinheiro que efetivamente entrou e saiu da conta do negócio em um período — diferente de faturamento, que pode incluir vendas ainda não recebidas.",
    howCalculated: "Entradas efetivas menos saídas efetivas do período (fluxo líquido); somado ao saldo inicial dá o saldo final.",
    whyItMatters: "É o que decide se há dinheiro disponível para pagar contas amanhã, mesmo que o negócio esteja tecnicamente lucrativo no papel.",
    whatCanChangeIt: "Atraso de recebíveis, antecipação de pagamentos, sazonalidade de vendas, novos investimentos.",
    whatCanUserDo: "Acompanhar o fluxo de caixa semanalmente, não só o resultado mensal, para antecipar apertos.",
  },
  {
    id: "reserva-caixa",
    simpleLabel: "Dinheiro protegido para períodos difíceis",
    technicalTerm: "Reserva de caixa",
    whatIsIt: "Uma parte do saldo disponível separada mentalmente (ou em conta apartada) para cobrir despesas essenciais em meses ruins.",
    howCalculated: "Recomendação = gastos essenciais mensais × número de meses de proteção desejado.",
    whyItMatters: "Sem reserva, uma queda de vendas de um único mês pode comprometer o pagamento de aluguel e folha.",
    whatCanChangeIt: "Aumento dos gastos essenciais, retirada de sócio, meses seguidos de resultado negativo.",
    whatCanUserDo: "Definir uma meta de meses de proteção e acompanhar o percentual atingido mês a mês.",
  },
  {
    id: "cobertura-caixa",
    simpleLabel: "Tempo que a empresa sobreviveria sem novas vendas",
    technicalTerm: "Cobertura de caixa",
    whatIsIt: "Quantos meses a reserva disponível sustenta as despesas essenciais se nenhuma nova venda acontecer.",
    howCalculated: "Reserva disponível dividido pelos gastos essenciais mensais.",
    whyItMatters: "É a pergunta mais direta sobre resiliência financeira: 'se parar de vender hoje, até quando eu aguento?'",
    whatCanChangeIt: "Tamanho da reserva, nível dos gastos essenciais, cenário de queima de caixa considerado.",
    whatCanUserDo: "Olhar os três cenários (conservador, provável, otimista) antes de decidir se está confortável ou não.",
  },
  {
    id: "capital-giro",
    simpleLabel: "Dinheiro necessário entre pagar e receber",
    technicalTerm: "Capital de giro",
    whatIsIt: "O valor que o negócio precisa ter disponível para cobrir o intervalo entre pagar fornecedores/despesas e efetivamente receber das vendas.",
    howCalculated: "Estimativa gerencial a partir do calendário de contas a pagar e a receber — não é um cálculo contábil definitivo.",
    whyItMatters: "Negócios lucrativos podem quebrar por falta de capital de giro se o prazo de pagamento for menor que o de recebimento.",
    whatCanChangeIt: "Prazo dos fornecedores, prazo de recebimento de vendas (à vista vs. parcelado), sazonalidade.",
    whatCanUserDo: "Negociar prazos com fornecedores e formas de pagamento com clientes para reduzir esse intervalo.",
  },
  {
    id: "planejado",
    simpleLabel: "Valor esperado antes do período começar",
    technicalTerm: "Planejado",
    whatIsIt: "Uma estimativa de receita ou despesa definida antes do período acontecer, usada como referência de comparação.",
    howCalculated: "Definido manualmente ou importado de planilha antes do fechamento do período.",
    whyItMatters: "Sem um planejado, não há como saber se o resultado realizado foi bom ou ruim — só se ele existiu.",
    whatCanChangeIt: "Mudança de meta, sazonalidade prevista, novos contratos ou investimentos programados.",
    whatCanUserDo: "Revisar o planejado regularmente para que a comparação com o realizado continue fazendo sentido.",
  },
  {
    id: "realizado",
    simpleLabel: "Valor que realmente aconteceu",
    technicalTerm: "Realizado",
    whatIsIt: "O valor efetivamente recebido ou pago, com data e origem confirmadas — nunca uma expectativa.",
    howCalculated: "Soma dos lançamentos com status pago/recebido e data efetiva preenchida.",
    whyItMatters: "É a base de qualquer decisão financeira séria — planejado é intenção, realizado é fato.",
    whatCanChangeIt: "Qualquer entrada ou saída de dinheiro que efetivamente ocorreu.",
    whatCanUserDo: "Nunca tratar uma conta planejada ou pendente como se fosse dinheiro já disponível.",
  },
  {
    id: "queima-caixa",
    simpleLabel: "Velocidade com que o caixa está sendo consumido",
    technicalTerm: "Queima de caixa",
    whatIsIt: "O ritmo em que a reserva ou o saldo disponível diminui quando as saídas superam as entradas.",
    howCalculated: "Saídas essenciais médias mensais, ajustadas por um cenário (conservador, provável ou otimista).",
    whyItMatters: "Uma queima de caixa acelerada reduz a cobertura sem vendas mais rápido do que o esperado.",
    whatCanChangeIt: "Aumento de despesas fixas, queda de receita, decisões de investimento fora do planejado.",
    whatCanUserDo: "Monitorar a queima de caixa mensalmente e ajustar despesas não essenciais quando ela acelerar.",
  },
  {
    id: "preco-por-objetivo",
    simpleLabel: "Preço necessário para atingir a meta",
    technicalTerm: "Preço por objetivo",
    whatIsIt: "Uma referência calculada a partir do custo e da meta interna, separada do preço atual e da faixa de mercado.",
    howCalculated: "Custo considerado dividido pela meta de CMV; taxas e margem exigem cenários adicionais.",
    whyItMatters: "Mostra a tensão entre custo, meta e mercado sem chamar um único número de preço ideal.",
    whatCanChangeIt: "Custo, embalagem, canal, taxas, impostos configurados e meta escolhida.",
    whatCanUserDo: "Comparar com preço realizado e mercado e confirmar qualquer decisão manualmente.",
  },
  {
    id: "faixa-mercado",
    simpleLabel: "Faixa praticada por produtos semelhantes",
    technicalTerm: "Referência de mercado",
    whatIsIt: "O intervalo entre preços confirmados de produtos realmente comparáveis.",
    howCalculated: "Mínimo, mediana, média e máximo de amostras atuais e comparáveis; a mediana é a referência principal.",
    whyItMatters: "Evita decidir com base em um único concorrente ou em promoção temporária.",
    whatCanChangeIt: "Canal, região, composição, gramagem, posicionamento e atualidade da coleta.",
    whatCanUserDo: "Revisar comparabilidade e coletar novas amostras quando a confiança estiver baixa.",
  },
  {
    id: "posicao-preco",
    simpleLabel: "Diferença entre seu preço e o mercado",
    technicalTerm: "Posição de preço",
    whatIsIt: "Indica se o preço atual está abaixo, alinhado ou acima da mediana comparável.",
    howCalculated: "Diferença percentual entre o preço atual e a mediana do benchmark.",
    whyItMatters: "Ajuda a testar se diferenciais percebidos sustentam um posicionamento superior.",
    whatCanChangeIt: "Amostra, canal, descontos, qualidade e proposta de valor.",
    whatCanUserDo: "Usar como hipótese, nunca como ordem automática de reajuste.",
  },
  {
    id: "custo-maximo-permitido",
    simpleLabel: "Quanto o produto pode custar para manter a meta",
    technicalTerm: "Custo máximo permitido",
    whatIsIt: "O teto de custo compatível com um preço e uma meta de CMV escolhidos.",
    howCalculated: "Preço de venda multiplicado pela meta de CMV.",
    whyItMatters: "Mostra quando alinhar ao mercado exigiria rever custo, rendimento ou proposta.",
    whatCanChangeIt: "Preço, meta, ficha técnica e custos considerados.",
    whatCanUserDo: "Investigar fornecedores e processo sem reduzir qualidade automaticamente.",
  },
  {
    id: "efeito-mix",
    simpleLabel: "Impacto dos produtos mais vendidos no custo geral",
    technicalTerm: "Efeito do mix",
    whatIsIt: "A mudança no CMV consolidado causada pela participação relativa dos produtos vendidos.",
    howCalculated: "Custo teórico total dos produtos vendidos dividido pela receita considerada.",
    whyItMatters: "Um CMV maior pode vir do mix, sem representar desperdício ou falha operacional.",
    whatCanChangeIt: "Volume por produto, preços realizados, descontos e canal.",
    whatCanUserDo: "Comparar períodos equivalentes e separar efeito do mix de lacunas operacionais.",
  },
  {
    id: "margem-contribuicao-unitaria",
    simpleLabel: "Valor que sobra por unidade vendida",
    technicalTerm: "Margem de contribuição unitária",
    whatIsIt: "Quanto uma unidade ajuda a pagar custos fixos depois dos custos variáveis atribuídos.",
    howCalculated: "Receita realizada unitária menos custos variáveis atribuídos.",
    whyItMatters: "É o eixo principal da engenharia de cardápio junto com popularidade.",
    whatCanChangeIt: "Preço, desconto, custo, embalagem, taxa e canal.",
    whatCanUserDo: "Comparar por canal e conferir taxas ausentes antes de agir.",
  },
  {
    id: "contribuicao-total",
    simpleLabel: "Valor total gerado pelo produto no período",
    technicalTerm: "Contribuição total",
    whatIsIt: "A soma da contribuição gerada por todas as unidades vendidas de um produto.",
    howCalculated: "Margem de contribuição unitária multiplicada pela quantidade vendida.",
    whyItMatters: "Um item de margem unitária menor pode ser muito relevante pelo volume.",
    whatCanChangeIt: "Margem unitária e quantidade vendida no período.",
    whatCanUserDo: "Analisar junto com popularidade, faturamento e função estratégica.",
  },
];

export function findStockGlossaryEntry(id: string): StockGlossaryEntry | undefined {
  return STOCK_GLOSSARY.find((e) => e.id === id);
}
